# Cloud Build configuration for AI Team Service
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/ai-team-service:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/ai-team-service:latest',
      '.'
    ]
    id: 'build-ai-team-service'

  # Run tests (if test files exist)
  - name: 'gcr.io/$PROJECT_ID/ai-team-service:$COMMIT_SHA'
    entrypoint: 'python'
    args: ['-c', 'print("AI Team Service built successfully")']
    env: ['ENVIRONMENT=test']
    id: 'test-ai-team-service'
    waitFor: ['build-ai-team-service']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-team-service:$COMMIT_SHA']
    id: 'push-ai-team-service-sha'
    waitFor: ['test-ai-team-service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-team-service:latest']
    id: 'push-ai-team-service-latest'
    waitFor: ['test-ai-team-service']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'ai-team-service'
    - '--image'
    - 'gcr.io/$PROJECT_ID/ai-team-service:$COMMIT_SHA'
    - '--platform'
    - 'managed'
    - '--region'
    - '${_DEPLOY_REGION}'
    - '--allow-unauthenticated'
    - '--max-instances'
    - '10'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--concurrency'
    - '80'
    - '--timeout'
    - '3600'
    - '--set-env-vars'
    - 'ENVIRONMENT=production,AI_MEMORY_BUCKET=chatterfix-ai-memory-$PROJECT_ID,ENABLE_MEMORY_SYSTEM=true'
    - '--set-secrets'
    - 'OPENAI_API_KEY=openai-api-key:latest,ANTHROPIC_API_KEY=anthropic-api-key:latest,GOOGLE_API_KEY=google-api-key:latest,XAI_API_KEY=xai-api-key:latest,INTERNAL_API_KEY=internal-api-key:latest'
    id: 'deploy-ai-team-service'
    waitFor: ['push-ai-team-service-sha']

  # Health check
  - name: 'gcr.io/cloud-builders/curl'
    args: [
      '--fail',
      '--retry', '3',
      '--retry-delay', '10',
      'https://ai-team-service-${_CLOUD_RUN_SUFFIX}.uc.r.appspot.com/health'
    ]
    id: 'health-check-ai-team'
    waitFor: ['deploy-ai-team-service']

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for entire build
timeout: '1200s'

# Substitutions
substitutions:
  _DEPLOY_REGION: 'us-central1'
  _CLOUD_RUN_SUFFIX: '${PROJECT_ID}'

# Images to store in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ai-team-service:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ai-team-service:latest'