steps:
  - name: 'python:3.11'
    id: 'Upgrade Pip'
    dir: 'chatterfix'
    entrypoint: 'pip'
    args: ["install", "--upgrade", "pip"]

  - name: 'python:3.11'
    id: 'Install Python Dependencies'
    dir: 'chatterfix'
    entrypoint: 'pip'
    args: ["install", "-r", "requirements.txt"]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend Docker Image'
    dir: 'chatterfix'
    args: ['build', '-t', 'gcr.io/gen-lang-client-0851999694/chatterfix-backend', '.']

  - name: 'node:20'
    id: 'Install Frontend Dependencies'
    dir: 'frontend'
    entrypoint: 'npm'
    args: ["install"]

  - name: 'node:20'
    id: 'Build Frontend'
    dir: 'frontend'
    entrypoint: 'npm'
    args: ["run", "build"]

timeout: 1200s
serviceAccount: 'chatterfix-builder@gen-lang-client-0851999694.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY