# Cloud Build CI/CD Pipeline for ChatterFix AI Services
# Designed with AI Team collaboration for continuous deployment
steps:
  # Build AI Services HTTP container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-services:$COMMIT_SHA', 
           '-f', 'services/ai-services/Dockerfile', './services/ai-services']
    id: 'build-ai-services'

  # Build AI Team gRPC container  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-team-grpc:$COMMIT_SHA',
           '-f', 'ai_team/Dockerfile.grpc', './ai_team']
    id: 'build-ai-team-grpc'

  # Run AI Services tests
  - name: 'gcr.io/$PROJECT_ID/ai-services:$COMMIT_SHA'
    entrypoint: 'python'
    args: ['-m', 'pytest', 'tests/', '-v']
    env: ['ENVIRONMENT=test']
    id: 'test-ai-services'
    waitFor: ['build-ai-services']

  # Push containers to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-services:$COMMIT_SHA']
    id: 'push-ai-services'
    waitFor: ['test-ai-services']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-team-grpc:$COMMIT_SHA']
    id: 'push-ai-team-grpc'
    waitFor: ['build-ai-team-grpc']

  # Deploy to Cloud Run (HTTP APIs)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'ai-services'
    - '--image'
    - 'gcr.io/$PROJECT_ID/ai-services:$COMMIT_SHA'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--max-instances'
    - '100'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--concurrency'
    - '80'
    - '--timeout'
    - '3600'
    - '--set-env-vars'
    - 'AI_TEAM_GRPC_URL=ai-team-grpc-service:50051,ENVIRONMENT=production,AI_MEMORY_BUCKET=chatterfix-ai-memory-$PROJECT_ID'
    - '--set-secrets'
    - 'OPENAI_API_KEY=openai-api-key:latest,ANTHROPIC_API_KEY=anthropic-api-key:latest,GOOGLE_API_KEY=google-api-key:latest,XAI_API_KEY=xai-api-key:latest'
    id: 'deploy-cloud-run'
    waitFor: ['push-ai-services']

  # Deploy to GKE (gRPC services)
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/ai-team-grpc', 
           'ai-team-grpc=gcr.io/$PROJECT_ID/ai-team-grpc:$COMMIT_SHA']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ai-services-cluster'
    id: 'deploy-gke'
    waitFor: ['push-ai-team-grpc']

  # Run post-deployment health checks
  - name: 'gcr.io/cloud-builders/curl'
    args: ['--fail', '--retry', '3', '--retry-delay', '10', 
           'https://ai-services-$PROJECT_ID.uc.r.appspot.com/health']
    id: 'health-check'
    waitFor: ['deploy-cloud-run']

# Trigger configuration
trigger:
  branch: '^main$'
  includedFiles:
  - 'services/ai-services/**'
  - 'ai_team/**'
  - 'cloudbuild.yaml'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
# Timeout for entire build
timeout: '1800s'

# Substitutions
substitutions:
  _DEPLOY_REGION: 'us-central1'
  _SERVICE_NAME: 'ai-services'