# Cloud Build configuration for ChatterFix CMMS
# Deploys to Google Cloud Run with Firebase/Firestore

steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/chatterfix-cmms:$BUILD_ID",
        "-t",
        "gcr.io/$PROJECT_ID/chatterfix-cmms:latest",
        ".",
      ]

  # Push the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/chatterfix-cmms:$BUILD_ID"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/chatterfix-cmms:latest"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "chatterfix",
        "--image",
        "gcr.io/$PROJECT_ID/chatterfix-cmms:$BUILD_ID",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8080",
        "--memory",
        "2Gi",
        "--cpu",
        "2",
        "--max-instances",
        "10",
        "--set-env-vars",
        "ENVIRONMENT=production,USE_FIRESTORE=true,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,CMMS_PORT=8080",
        "--service-account",
        "chatterfix-service@$PROJECT_ID.iam.gserviceaccount.com",
      ]

  # Update traffic to new revision
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "services",
        "update-traffic",
        "chatterfix",
        "--to-latest",
        "--region",
        "us-central1",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

# Store images in Container Registry
images:
  - "gcr.io/$PROJECT_ID/chatterfix-cmms:$BUILD_ID"
  - "gcr.io/$PROJECT_ID/chatterfix-cmms:latest"

# Timeout for the entire build
timeout: "1200s"
