#!/usr/bin/env python3
"""
ChatterFix CMMS Demo Data Population Script
Creates realistic demo data for a fully functional demonstration
"""

import random
from datetime import datetime, timedelta
import json

DATABASE_PATH = "./data/cmms.db"


def populate_demo_data():
    import sys
    import os

    sys.path.insert(0, os.path.dirname(__file__))
    from app.core.database import get_db_connection

    conn = get_db_connection()
    cursor = conn.cursor()

    # Clear existing demo data (keep structure)
    tables_to_clear = [
        "work_orders",
        "assets",
        "users",
        "parts",
        "maintenance_history",
        "vendors",
        "purchase_orders",
        "notifications",
        "schedules",
    ]

    for table in tables_to_clear:
        try:
            cursor.execute(f"DELETE FROM {table}")
            cursor.execute(f"UPDATE sqlite_sequence SET seq = 0 WHERE name = '{table}'")
        except:
            pass

    # ========== USERS ==========
    users_data = [
        (
            "admin",
            "admin@chatterfix.com",
            "$2b$12$dummy_hash",
            "Admin User",
            "manager",
            "+1-512-555-0001",
            "/static/images/admin.jpg",
            "available",
            1,
            "2023-01-15",
        ),
        (
            "sarah.chen",
            "sarah.chen@evfactory.com",
            "$2b$12$dummy_hash",
            "Sarah Chen",
            "manager",
            "+1-512-555-0002",
            "/static/images/sarah.jpg",
            "available",
            1,
            "2023-03-20",
        ),
        (
            "mike.rodriguez",
            "mike.rodriguez@evfactory.com",
            "$2b$12$dummy_hash",
            "Mike Rodriguez",
            "technician",
            "+1-512-555-0003",
            "/static/images/mike.jpg",
            "busy",
            1,
            "2023-04-12",
        ),
        (
            "alex.kim",
            "alex.kim@evfactory.com",
            "$2b$12$dummy_hash",
            "Alex Kim",
            "technician",
            "+1-512-555-0004",
            "/static/images/alex.jpg",
            "busy",
            1,
            "2023-05-08",
        ),
        (
            "jennifer.tang",
            "jennifer.tang@evfactory.com",
            "$2b$12$dummy_hash",
            "Jennifer Tang",
            "supervisor",
            "+1-512-555-0005",
            "/static/images/jennifer.jpg",
            "available",
            1,
            "2023-02-28",
        ),
        (
            "david.wilson",
            "david.wilson@evfactory.com",
            "$2b$12$dummy_hash",
            "David Wilson",
            "technician",
            "+1-512-555-0006",
            "/static/images/david.jpg",
            "available",
            1,
            "2023-06-15",
        ),
        (
            "lisa.johnson",
            "lisa.johnson@evfactory.com",
            "$2b$12$dummy_hash",
            "Lisa Johnson",
            "planner",
            "+1-512-555-0007",
            "/static/images/lisa.jpg",
            "available",
            1,
            "2023-03-10",
        ),
    ]

    for user in users_data:
        cursor.execute(
            """
            INSERT INTO users (username, email, password_hash, full_name, role, phone, avatar_url, status, is_active, created_date)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
            user,
        )

    # ========== ASSETS ==========
    assets_data = [
        # Production Line 1
        (
            "Battery Pack Assembly Line 1",
            "High-speed automated assembly line for EV battery packs",
            "BPAL-001",
            "BP2023-X1",
            "Model X1-2023",
            "EV Manufacturing Inc",
            "Production Floor A",
            "Manufacturing",
            "Active",
            9,
            "Critical",
            "2023-01-15",
            "2025-01-15",
            2500000.00,
            "2023-01-15",
            "2023-11-20",
            "2024-01-15",
            24.5,
            125000.00,
            "/static/images/battery_line.jpg",
        ),
        (
            "Gigapress Machine Alpha",
            "8000-ton casting machine for vehicle frames",
            "GPM-ALPHA",
            "GP-8K-001",
            "Giga Press 8000T",
            "IDRA Group",
            "Casting Bay 1",
            "Manufacturing",
            "Active",
            8,
            "Critical",
            "2023-02-01",
            "2030-02-01",
            15000000.00,
            "2023-02-01",
            "2023-11-10",
            "2024-02-01",
            18.2,
            85000.00,
            "/static/images/gigapress.jpg",
        ),
        (
            "Paint Booth Station 3",
            "Automated paint application system with color changing capability",
            "PBS-003",
            "PB-AC-2023",
            "AutoCoat Pro 5000",
            "Dürr Systems",
            "Paint Shop",
            "Finishing",
            "Active",
            7,
            "High",
            "2023-01-20",
            "2028-01-20",
            750000.00,
            "2023-01-20",
            "2023-11-05",
            "2024-01-20",
            36.8,
            45000.00,
            "/static/images/paint_booth.jpg",
        ),
        (
            "Stamping Press Line B",
            "Heavy-duty stamping press for body panels",
            "SPL-B-01",
            "SP-HD-450",
            "HeavyDuty 450T",
            "Schuler Group",
            "Stamping Bay B",
            "Manufacturing",
            "Active",
            8,
            "Critical",
            "2023-03-10",
            "2033-03-10",
            3200000.00,
            "2023-03-10",
            "2023-10-28",
            "2024-03-10",
            12.5,
            95000.00,
            "/static/images/stamping_press.jpg",
        ),
        # Supporting Equipment
        (
            "Compressed Air System",
            "Central compressed air distribution system",
            "CAS-001",
            "CA-CTL-2023",
            "CentralAir 5000",
            "Atlas Copco",
            "Utility Room 1",
            "Utilities",
            "Active",
            8,
            "High",
            "2023-01-05",
            "2030-01-05",
            125000.00,
            "2023-01-05",
            "2023-10-25",
            "2024-01-05",
            8.5,
            15000.00,
            "/static/images/air_system.jpg",
        ),
        (
            "Electrical Substation A",
            "Main power distribution substation",
            "ESA-001",
            "ES-PWR-500",
            "PowerGrid 500kV",
            "ABB",
            "Electrical Room A",
            "Electrical",
            "Active",
            9,
            "Critical",
            "2022-12-15",
            "2032-12-15",
            850000.00,
            "2022-12-15",
            "2023-10-20",
            "2024-12-15",
            6.0,
            32000.00,
            "/static/images/substation.jpg",
        ),
        (
            "Cooling Tower System",
            "Industrial cooling system for process equipment",
            "CTS-001",
            "CT-IND-2000",
            "CoolMax 2000",
            "Baltimore Aircoil",
            "Rooftop",
            "HVAC",
            "Active",
            7,
            "High",
            "2023-02-20",
            "2033-02-20",
            180000.00,
            "2023-02-20",
            "2023-10-15",
            "2024-02-20",
            16.2,
            25000.00,
            "/static/images/cooling_tower.jpg",
        ),
        (
            "AGV Fleet Controller",
            "Automated guided vehicle fleet management system",
            "AGV-FC-01",
            "AGV-FM-2023",
            "FleetMaster 3000",
            "KION Group",
            "Control Room",
            "Automation",
            "Active",
            8,
            "Medium",
            "2023-04-01",
            "2028-04-01",
            95000.00,
            "2023-04-01",
            "2023-10-10",
            "2024-04-01",
            4.5,
            5000.00,
            "/static/images/agv_system.jpg",
        ),
        # Quality & Testing
        (
            "X-Ray Inspection Unit",
            "Battery pack quality inspection system",
            "XIU-001",
            "XR-QC-450",
            "InspectPro X450",
            "Yxlon",
            "Quality Lab",
            "Quality",
            "Active",
            8,
            "High",
            "2023-03-15",
            "2030-03-15",
            320000.00,
            "2023-03-15",
            "2023-10-01",
            "2024-03-15",
            12.8,
            18000.00,
            "/static/images/xray_unit.jpg",
        ),
        (
            "Leak Test Station",
            "Automated leak detection for battery systems",
            "LTS-002",
            "LT-AUTO-100",
            "LeakGuard 100",
            "ATEQ",
            "Quality Lab",
            "Quality",
            "Active",
            9,
            "High",
            "2023-05-01",
            "2030-05-01",
            85000.00,
            "2023-05-01",
            "2023-11-22",
            "2024-05-01",
            6.2,
            8500.00,
            "/static/images/leak_tester.jpg",
        ),
        # Maintenance Equipment
        (
            "Mobile Crane Unit 5",
            "50-ton mobile crane for heavy lifting",
            "MCU-005",
            "MC-HD-50T",
            "CraneMaster 50",
            "Liebherr",
            "Maintenance Bay",
            "Maintenance",
            "Active",
            8,
            "High",
            "2023-02-10",
            "2033-02-10",
            450000.00,
            "2023-02-10",
            "2023-11-20",
            "2024-02-10",
            8.0,
            22000.00,
            "/static/images/crane.jpg",
        ),
        (
            "Forklift Fleet A1",
            "Electric forklift for material handling",
            "FFA-001",
            "FL-EL-5000",
            "ElectroLift 5000",
            "Toyota",
            "Warehouse",
            "Material Handling",
            "Active",
            7,
            "Medium",
            "2023-04-15",
            "2030-04-15",
            35000.00,
            "2023-04-15",
            "2023-11-20",
            "2024-04-15",
            28.5,
            12000.00,
            "/static/images/forklift.jpg",
        ),
    ]

    for asset in assets_data:
        cursor.execute(
            """
            INSERT INTO assets (name, description, asset_tag, serial_number, model, manufacturer, 
                               location, department, status, condition_rating, criticality, 
                               purchase_date, warranty_expiry, purchase_cost, installation_date, 
                               last_maintenance_date, next_maintenance_due, total_downtime_hours, 
                               total_maintenance_cost, image_url)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
            asset,
        )

    # ========== PARTS INVENTORY ==========
    parts_data = [
        # Battery Line Parts
        (
            "Battery Cell 2170",
            "High-performance lithium-ion battery cell",
            "BC-2170-001",
            "Battery Components",
            2500,
            500,
            "Bin A1-001",
            15.50,
            2,
            "/static/images/battery_cell.jpg",
        ),
        (
            "Battery Pack Housing",
            "Aluminum housing for battery pack assembly",
            "BPH-ALU-001",
            "Structural Components",
            45,
            10,
            "Rack B2-015",
            285.00,
            1,
            "/static/images/battery_housing.jpg",
        ),
        (
            "Cooling Plate Assembly",
            "Liquid cooling plate for battery thermal management",
            "CPA-LIQ-001",
            "Cooling System",
            120,
            25,
            "Bin C1-008",
            125.75,
            1,
            "/static/images/cooling_plate.jpg",
        ),
        # Gigapress Parts
        (
            "Hydraulic Cylinder Seal",
            "High-pressure seal for gigapress hydraulic system",
            "HCS-HP-001",
            "Hydraulic Components",
            85,
            15,
            "Bin D2-003",
            45.20,
            6,
            "/static/images/hydraulic_seal.jpg",
        ),
        (
            "Die Insert Set",
            "Precision die insert for aluminum casting",
            "DIS-AL-001",
            "Tooling",
            8,
            2,
            "Tool Crib 1",
            12500.00,
            3,
            "/static/images/die_insert.jpg",
        ),
        (
            "Lubrication Pump",
            "Automatic lubrication pump for gigapress",
            "LP-AUTO-001",
            "Lubrication System",
            12,
            3,
            "Rack E1-012",
            850.30,
            5,
            "/static/images/lube_pump.jpg",
        ),
        # Paint System Parts
        (
            "Paint Nozzle Assembly",
            "Precision paint application nozzle",
            "PNA-PREC-001",
            "Paint Application",
            95,
            20,
            "Cabinet F1-005",
            185.60,
            4,
            "/static/images/paint_nozzle.jpg",
        ),
        (
            "Color Change Valve",
            "Quick color change valve for paint system",
            "CCV-QC-001",
            "Paint System",
            24,
            5,
            "Cabinet F2-008",
            425.80,
            4,
            "/static/images/color_valve.jpg",
        ),
        (
            "Overspray Filter",
            "High-efficiency overspray capture filter",
            "OSF-HE-001",
            "Filtration",
            180,
            30,
            "Storage F3-001",
            65.25,
            7,
            "/static/images/overspray_filter.jpg",
        ),
        # General Maintenance
        (
            "Industrial Bearing 6324",
            "Heavy-duty industrial bearing",
            "IB-6324-001",
            "Bearings",
            75,
            15,
            "Bin G1-001",
            125.40,
            5,
            "/static/images/bearing.jpg",
        ),
        (
            "V-Belt 5VX1250",
            "High-performance V-belt",
            "VB-5VX1250",
            "Belts",
            150,
            25,
            "Rack G2-005",
            28.75,
            7,
            "/static/images/vbelt.jpg",
        ),
        (
            "Hydraulic Fluid 46",
            "High-quality hydraulic fluid",
            "HF-46-001",
            "Fluids",
            85,
            20,
            "Tank G3-001",
            22.50,
            7,
            "/static/images/hydraulic_fluid.jpg",
        ),
        (
            "Safety Relay Module",
            "Industrial safety relay for machine protection",
            "SRM-IND-001",
            "Electrical",
            35,
            8,
            "Cabinet H1-003",
            145.80,
            7,
            "/static/images/safety_relay.jpg",
        ),
        (
            "Pneumatic Cylinder",
            "Double-acting pneumatic cylinder",
            "PC-DA-001",
            "Pneumatic Components",
            45,
            10,
            "Bin H2-007",
            185.20,
            7,
            "/static/images/pneumatic_cylinder.jpg",
        ),
    ]

    for part in parts_data:
        cursor.execute(
            """
            INSERT INTO parts (name, description, part_number, category, current_stock, 
                              minimum_stock, location, unit_cost, vendor_id, image_url)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
            part,
        )

    # ========== WORK ORDERS ==========
    work_orders_data = [
        # Critical/In Progress
        (
            "Battery Line 1 - Conveyor Belt Replacement",
            "Replace worn conveyor belt on station 3 of battery assembly line. Belt showing signs of excessive wear and causing misalignment.",
            "In Progress",
            "Critical",
            "Mike Rodriguez",
            1,
            "2024-11-28",
            "2024-11-29",
        ),
        (
            "Gigapress Alpha - Hydraulic Pressure Drop",
            "Investigate and repair hydraulic pressure inconsistency. Pressure dropping from 8000psi to 7200psi during operation cycles.",
            "In Progress",
            "Critical",
            "Alex Kim",
            2,
            "2024-11-27",
            "2024-11-29",
        ),
        (
            "Paint Booth 3 - Color Change Malfunction",
            "Color change system not switching properly between colors. Manual override required for each color change.",
            "In Progress",
            "High",
            "David Wilson",
            3,
            "2024-11-28",
            "2024-11-30",
        ),
        # Open/Scheduled
        (
            "Stamping Press B - Scheduled 10K Hour Maintenance",
            "Perform comprehensive 10,000 hour maintenance including lubrication, alignment check, and safety system verification.",
            "Open",
            "High",
            "Jennifer Tang",
            4,
            "2024-12-02",
            "2024-12-05",
        ),
        (
            "Compressed Air System - Filter Replacement",
            "Replace primary and secondary air filters. Current filters at 85% capacity.",
            "Open",
            "Medium",
            "",
            5,
            "2024-12-01",
            "2024-12-01",
        ),
        (
            "Electrical Substation A - Quarterly Inspection",
            "Quarterly electrical safety inspection and thermal imaging scan of all connections.",
            "Open",
            "High",
            "Lisa Johnson",
            6,
            "2024-12-03",
            "2024-12-03",
        ),
        (
            "X-Ray Unit - Calibration Service",
            "Annual calibration service for X-ray inspection unit. Required for quality certification.",
            "Open",
            "Medium",
            "",
            9,
            "2024-12-05",
            "2024-12-06",
        ),
        # Recently Completed
        (
            "Cooling Tower - Chemical Treatment",
            "Applied biocide and scale inhibitor to cooling tower system. Water chemistry now within optimal range.",
            "Completed",
            "Medium",
            "Mike Rodriguez",
            7,
            "2024-11-25",
            "2024-11-26",
        ),
        (
            "AGV Fleet - Software Update",
            "Updated fleet management software to v3.2.1. Improved navigation algorithms and battery optimization.",
            "Completed",
            "Low",
            "Alex Kim",
            8,
            "2024-11-24",
            "2024-11-24",
        ),
        (
            "Forklift A1 - Annual Inspection",
            "Completed annual safety inspection. All systems operational. Next inspection due November 2025.",
            "Completed",
            "Medium",
            "David Wilson",
            12,
            "2024-11-20",
            "2024-11-20",
        ),
        (
            "Leak Test Station - Sensor Calibration",
            "Calibrated leak detection sensors. System now detecting leaks down to 0.1 sccm sensitivity.",
            "Completed",
            "High",
            "Jennifer Tang",
            10,
            "2024-11-22",
            "2024-11-23",
        ),
        # Predictive Maintenance
        (
            "Battery Line 1 - Predictive: Motor Bearing Replacement",
            "AI system detected bearing vibration anomaly. Recommend replacement before failure occurs.",
            "Open",
            "Medium",
            "",
            1,
            "2024-12-10",
            "2024-12-12",
        ),
        (
            "Paint Booth 3 - Predictive: Fan Motor Service",
            "Thermal analysis indicates motor running 15°C above normal. Schedule service to prevent failure.",
            "Open",
            "Medium",
            "",
            3,
            "2024-12-08",
            "2024-12-09",
        ),
    ]

    for wo in work_orders_data:
        cursor.execute(
            """
            INSERT INTO work_orders (title, description, status, priority, assigned_to, 
                                   asset_id, created_date, due_date)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
            wo,
        )

    # ========== MAINTENANCE HISTORY ==========
    maintenance_history = [
        (
            1,
            None,
            "Preventive",
            "Performed weekly lubrication and visual inspection. All systems normal.",
            "Mike Rodriguez",
            "2024-11-21 08:00:00",
            "2024-11-21 10:30:00",
            0.0,
            125.00,
            25.50,
            150.50,
            "All systems operational",
            "2024-11-21",
        ),
        (
            1,
            None,
            "Corrective",
            "Replaced faulty sensor on station 2. System restored to full operation.",
            "Alex Kim",
            "2024-11-15 14:00:00",
            "2024-11-15 18:00:00",
            4.0,
            200.00,
            85.75,
            285.75,
            "Sensor replaced, calibration completed",
            "2024-11-15",
        ),
        (
            2,
            None,
            "Preventive",
            "Monthly hydraulic system service. Replaced filters and checked fluid levels.",
            "Jennifer Tang",
            "2024-11-10 06:00:00",
            "2024-11-10 12:00:00",
            0.0,
            300.00,
            150.25,
            450.25,
            "Hydraulic system serviced",
            "2024-11-10",
        ),
        (
            3,
            None,
            "Preventive",
            "Recalibrated paint thickness sensors. System now within specification.",
            "David Wilson",
            "2024-11-05 16:00:00",
            "2024-11-05 19:00:00",
            0.0,
            150.00,
            30.00,
            180.00,
            "Calibration successful",
            "2024-11-05",
        ),
        (
            4,
            None,
            "Preventive",
            "Safety system inspection completed. All emergency stops functional.",
            "Lisa Johnson",
            "2024-10-28 09:00:00",
            "2024-10-28 10:30:00",
            0.0,
            75.00,
            20.50,
            95.50,
            "Safety systems verified",
            "2024-10-28",
        ),
        (
            5,
            None,
            "Corrective",
            "Repaired air leak in main distribution line. Pressure restored to normal.",
            "Mike Rodriguez",
            "2024-10-25 11:00:00",
            "2024-10-25 14:30:00",
            3.5,
            140.00,
            25.80,
            165.80,
            "Air leak repaired",
            "2024-10-25",
        ),
        (
            6,
            None,
            "Preventive",
            "Quarterly electrical panel cleaning and connection tightening.",
            "Alex Kim",
            "2024-10-20 07:00:00",
            "2024-10-20 12:00:00",
            0.0,
            250.00,
            70.45,
            320.45,
            "Electrical maintenance completed",
            "2024-10-20",
        ),
        (
            7,
            None,
            "Preventive",
            "Applied quarterly chemical treatment to cooling system.",
            "David Wilson",
            "2024-10-15 10:00:00",
            "2024-10-15 12:00:00",
            0.0,
            100.00,
            185.60,
            285.60,
            "Chemical treatment applied",
            "2024-10-15",
        ),
        (
            8,
            None,
            "Preventive",
            "Updated AGV navigation software to improve efficiency.",
            "Jennifer Tang",
            "2024-10-10 20:00:00",
            "2024-10-10 21:00:00",
            0.0,
            50.00,
            0.00,
            50.00,
            "Software update completed",
            "2024-10-10",
        ),
        (
            9,
            None,
            "Preventive",
            "Annual X-ray system calibration completed successfully.",
            "Lisa Johnson",
            "2024-10-01 08:00:00",
            "2024-10-01 16:00:00",
            0.0,
            500.00,
            750.00,
            1250.00,
            "Calibration certificate issued",
            "2024-10-01",
        ),
    ]

    for mh in maintenance_history:
        cursor.execute(
            """
            INSERT INTO maintenance_history (asset_id, work_order_id, maintenance_type, description, 
                                           technician, start_time, end_time, downtime_hours, 
                                           labor_cost, parts_cost, total_cost, notes, created_date)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
            mh,
        )

    # ========== VENDORS ==========
    vendors_data = [
        (
            "EV Manufacturing Inc",
            "EV Factory Team",
            "internal@evfactory.com",
            "(512) 555-0100",
            "1 Electric Ave, Austin, TX 78725",
            "https://evfactory.com",
        ),
        (
            "Panasonic Corporation",
            "John Smith",
            "industrial@panasonic.com",
            "(973) 555-0200",
            "1 Panasonic Way, Newark, NJ 07102",
            "https://panasonic.com",
        ),
        (
            "IDRA Group",
            "Marco Rossi",
            "service@idra.it",
            "+39 030 555-0300",
            "Via Roma 136, Brescia, Italy",
            "https://idra.it",
        ),
        (
            "Dürr Systems AG",
            "Hans Mueller",
            "service@durr.com",
            "+49 7142 555-0400",
            "Carl-Benz-Str. 34, Bietigheim-Bissingen, Germany",
            "https://durr.com",
        ),
        (
            "SKF Group",
            "Sarah Johnson",
            "industrial@skf.com",
            "(909) 555-0500",
            "415 N Lone Hill Ave, San Dimas, CA 91773",
            "https://skf.com",
        ),
        (
            "Parker Hannifin",
            "Mike Davis",
            "hydraulics@parker.com",
            "(216) 555-0600",
            "6035 Parkland Blvd, Cleveland, OH 44124",
            "https://parker.com",
        ),
        (
            "Atlas Copco",
            "Emma Wilson",
            "service@atlascopco.com",
            "(803) 555-0700",
            "2200 Days Road, Rock Hill, SC 29730",
            "https://atlascopco.com",
        ),
    ]

    for vendor in vendors_data:
        cursor.execute(
            """
            INSERT INTO vendors (name, contact_name, email, phone, address, website)
            VALUES (?, ?, ?, ?, ?, ?)
        """,
            vendor,
        )

    # ========== NOTIFICATIONS ==========
    notifications_data = [
        (
            2,
            "equipment_alert",
            "Critical Alert",
            "Gigapress Alpha hydraulic pressure dropped below critical threshold",
            "/assets/2",
            0,
            "high",
            "2024-11-28 14:30:00",
        ),
        (
            3,
            "maintenance_due",
            "Maintenance Alert",
            "Battery Line 1 conveyor belt showing increased vibration",
            "/work-orders/1",
            0,
            "normal",
            "2024-11-28 09:15:00",
        ),
        (
            4,
            "scheduled_maintenance",
            "Scheduled Maintenance",
            "Paint Booth 3 scheduled for maintenance window this weekend",
            "/work-orders/3",
            1,
            "low",
            "2024-11-27 16:45:00",
        ),
        (
            2,
            "maintenance_due",
            "Filter Replacement Due",
            "Compressed air system filter replacement due within 48 hours",
            "/work-orders/5",
            0,
            "normal",
            "2024-11-28 08:00:00",
        ),
        (
            7,
            "calibration_complete",
            "Calibration Complete",
            "X-ray inspection unit calibration completed successfully",
            "/assets/9",
            1,
            "low",
            "2024-11-26 11:20:00",
        ),
        (
            3,
            "optimization_success",
            "Efficiency Improved",
            "Battery Line 1 efficiency increased 5% after optimization",
            "/assets/1",
            1,
            "low",
            "2024-11-25 15:30:00",
        ),
    ]

    for notification in notifications_data:
        cursor.execute(
            """
            INSERT INTO notifications (user_id, notification_type, title, message, link, read, priority, created_date)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
            notification,
        )

    # Note: Schedules table may not exist in this version

    conn.commit()
    conn.close()
    print("✅ Demo data populated successfully!")
    print("📊 Data Summary:")
    print(f"   • {len(users_data)} Users")
    print(f"   • {len(assets_data)} Assets")
    print(f"   • {len(parts_data)} Parts")
    print(f"   • {len(work_orders_data)} Work Orders")
    print(f"   • {len(maintenance_history)} Maintenance Records")
    print(f"   • {len(vendors_data)} Vendors")
    print(f"   • {len(notifications_data)} Notifications")


if __name__ == "__main__":
    populate_demo_data()
