#!/usr/bin/env python3
"""
Production Setup Script for ChatterFix CMMS
Sets up Firebase and production environment for GCP deployment
"""

import os
import sys
import subprocess
import json
from pathlib import Path


def check_gcp_environment():
    """Check if running on GCP or local"""
    try:
        # Try to get metadata token (available on GCP instances)
        result = subprocess.run(
            [
                "curl",
                "-s",
                "-H",
                "Metadata-Flavor: Google",
                "http://metadata.google.internal/computeMetadata/v1/project/project-id",
            ],
            capture_output=True,
            text=True,
            timeout=5,
        )

        if result.returncode == 0 and result.stdout:
            print(f"🌐 Running on GCP - Project: {result.stdout}")
            return True, result.stdout.strip()
    except:
        pass

    print("💻 Running locally")
    return False, None


def install_firebase_deps():
    """Install Firebase dependencies"""
    print("📦 Installing Firebase dependencies...")

    packages = [
        "firebase-admin>=6.4.0",
        "pyrebase4>=4.7.1",
        "google-cloud-firestore>=2.13.1",
        "google-cloud-storage>=2.13.0",
        "google-auth>=2.25.2",
    ]

    for package in packages:
        try:
            print(f"   Installing {package}...")
            subprocess.run(
                [sys.executable, "-m", "pip", "install", package],
                check=True,
                capture_output=True,
            )
            print(f"   ✅ {package} installed")
        except subprocess.CalledProcessError as e:
            print(f"   ❌ Failed to install {package}: {e}")
            return False

    return True


def setup_gcp_environment():
    """Set up environment for GCP"""
    print("🔧 Configuring for GCP deployment...")

    # Update environment file for production
    env_content = """# ChatterFix Production Configuration (GCP)
# Generated by setup_production.py

# Firebase Configuration (Production)
USE_FIRESTORE=true
GOOGLE_CLOUD_PROJECT=fredfix

# Production mode
ENVIRONMENT=production
CMMS_PORT=8080

# AI Configuration
GEMINI_API_KEY=AIzaSyDxQ45QqBacpEIISrS52E1QjeSy1nNuy48

# Security
SECRET_KEY=your-secret-key-here

# Disable local SQLite for production
DISABLE_SQLITE=true
"""

    with open(".env.production", "w") as f:
        f.write(env_content)

    print("✅ Production environment configured (.env.production)")
    return True


def setup_local_development():
    """Set up for local development"""
    print("🔧 Configuring for local development...")

    # Check if credentials file exists
    creds_path = "./firebase-credentials.json"
    if not os.path.exists(creds_path):
        print(f"⚠️ Firebase credentials not found at {creds_path}")
        print("   📋 To complete setup:")
        print("   1. Go to Firebase Console: https://console.firebase.google.com/")
        print("   2. Select project 'fredfix'")
        print("   3. Project Settings → Service accounts")
        print("   4. Generate new private key")
        print("   5. Save as firebase-credentials.json")
        return False

    # Update .env for local development
    env_vars = {
        "USE_FIRESTORE": "true",
        "GOOGLE_CLOUD_PROJECT": "fredfix",
        "GOOGLE_APPLICATION_CREDENTIALS": "./firebase-credentials.json",
    }

    # Read existing .env
    env_lines = []
    if os.path.exists(".env"):
        with open(".env", "r") as f:
            for line in f:
                key = line.split("=")[0] if "=" in line else ""
                if key not in env_vars:
                    env_lines.append(line.rstrip())

    # Add/update Firebase vars
    for key, value in env_vars.items():
        env_lines.append(f"{key}={value}")

    with open(".env", "w") as f:
        f.write("\n".join(env_lines))

    print("✅ Local development environment configured")
    return True


def test_firebase_connection():
    """Test Firebase connection"""
    print("🧪 Testing Firebase connection...")

    try:
        # Import and test Firebase
        import firebase_admin
        from firebase_admin import credentials, firestore

        # Check for credentials
        creds_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

        if creds_path and os.path.exists(creds_path):
            cred = credentials.Certificate(creds_path)
            if not firebase_admin._apps:
                app = firebase_admin.initialize_app(
                    cred, {"projectId": os.getenv("GOOGLE_CLOUD_PROJECT", "fredfix")}
                )
            else:
                app = firebase_admin.get_app()

            # Test Firestore
            db = firestore.client()

            # Simple test write/read
            test_doc = db.collection("_test").document("connection")
            test_doc.set({"timestamp": firestore.SERVER_TIMESTAMP, "test": True})

            # Read back
            doc = test_doc.get()
            if doc.exists:
                test_doc.delete()  # Clean up
                print("✅ Firebase connection successful!")
                return True
            else:
                print("❌ Firebase write/read test failed")
                return False
        else:
            # Try Application Default Credentials (GCP)
            try:
                cred = credentials.ApplicationDefault()
                if not firebase_admin._apps:
                    app = firebase_admin.initialize_app(
                        cred,
                        {"projectId": os.getenv("GOOGLE_CLOUD_PROJECT", "fredfix")},
                    )

                db = firestore.client()
                test_doc = db.collection("_test").document("connection")
                test_doc.set({"timestamp": firestore.SERVER_TIMESTAMP, "test": True})
                test_doc.delete()

                print(
                    "✅ Firebase connection successful (Application Default Credentials)!"
                )
                return True
            except Exception as e:
                print(f"❌ Firebase ADC test failed: {e}")
                return False

    except ImportError as e:
        print(f"❌ Firebase modules not available: {e}")
        return False
    except Exception as e:
        print(f"❌ Firebase test failed: {e}")
        return False


def main():
    """Main setup function"""
    print("🚀 ChatterFix Production Setup")
    print("=" * 50)

    # Detect environment
    is_gcp, project_id = check_gcp_environment()

    # Install dependencies
    if not install_firebase_deps():
        print("❌ Failed to install Firebase dependencies")
        return False

    # Setup environment
    if is_gcp:
        if not setup_gcp_environment():
            print("❌ GCP environment setup failed")
            return False
    else:
        if not setup_local_development():
            print("❌ Local development setup failed")
            return False

    # Test connection
    if test_firebase_connection():
        print("\n🎉 Setup Complete!")
        print("✅ Firebase configured and tested")
        print("🔥 ChatterFix ready for production on GCP")

        if is_gcp:
            print("\n🚀 To deploy:")
            print("   gcloud run deploy chatterfix --source .")
        else:
            print("\n🏃 To run locally:")
            print("   python main.py")

        return True
    else:
        print("\n❌ Setup incomplete - Firebase connection failed")
        return False


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
