name: Feature Request
description: Suggest a new feature for ChatterFix
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand what you need.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? What's the current pain point?
      placeholder: As a technician, I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      options:
        - Work Orders
        - Assets
        - Inventory
        - Dashboard
        - Voice Commands
        - Mobile App
        - AI/Automation
        - Training
        - Reporting
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: user
    attributes:
      label: Primary User
      description: Who benefits most from this feature?
      options:
        - Technician (field worker)
        - Manager
        - Admin
        - All users
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have
        - Would improve workflow
        - Critical for adoption

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternatives you've tried?
