runtime: python314
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.60

env_variables:
  CMMS_PORT: "8080"
  CMMS_DB_PATH: "./data/cmms.db"
  
# Handlers for static files
handlers:
- url: /static
  static_dir: app/static
  secure: always

- url: /.*
  script: auto
  secure: always
