apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chatterfix-cmms
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        autoscaling.knative.dev/maxScale: "20"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      serviceAccountName: chatterfix-service-account
      containers:
      - name: chatterfix-cmms
        image: gcr.io/PROJECT_ID/chatterfix-cmms:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: USE_FIRESTORE
          value: "true"
        - name: GOOGLE_CLOUD_PROJECT
          value: PROJECT_ID
        - name: LOG_LEVEL
          value: "info"
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3