"""
Enterprise Permission Matrix
Generated by OpenAI for ChatterFix CMMS
Comprehensive RBAC permissions following Least Privilege principle
"""

from enum import Enum
from typing import Dict, List


class Permission(Enum):
    """Enumeration of all available permissions in the CMMS system"""

    # Asset Management Permissions
    ASSET_READ = "asset:read"
    ASSET_WRITE = "asset:write"
    ASSET_DELETE = "asset:delete"
    ASSET_REGISTER = "asset:register"
    ASSET_TRANSFER = "asset:transfer"

    # Work Order Permissions
    WORK_ORDER_READ = "work_order:read"
    WORK_ORDER_CREATE = "work_order:create"
    WORK_ORDER_ASSIGN = "work_order:assign"
    WORK_ORDER_APPROVE = "work_order:approve"
    WORK_ORDER_COMPLETE = "work_order:complete"
    WORK_ORDER_DELETE = "work_order:delete"
    WORK_ORDER_RESCHEDULE = "work_order:reschedule"
    WORK_ORDER_PRIORITY_CHANGE = "work_order:priority_change"

    # Inventory Management Permissions
    INVENTORY_VIEW = "inventory:view"
    INVENTORY_UPDATE = "inventory:update"
    INVENTORY_PURCHASE = "inventory:purchase"
    INVENTORY_AUDIT = "inventory:audit"
    INVENTORY_WRITE_OFF = "inventory:write_off"
    INVENTORY_TRANSFER = "inventory:transfer"

    # User Management Permissions
    USER_VIEW_PROFILES = "user_management:view_profiles"
    USER_MANAGE_ACCOUNTS = "user_management:manage_accounts"
    USER_ASSIGN_ROLES = "user_management:assign_roles"
    USER_DELETE_ACCOUNTS = "user_management:delete_accounts"
    USER_VIEW_ACTIVITY = "user_management:view_activity"

    # System Administration Permissions
    SYSTEM_CONFIG = "system_admin:config"
    SYSTEM_BACKUP = "system_admin:backup"
    SYSTEM_RESTORE = "system_admin:restore"
    SYSTEM_LOGS = "system_admin:logs"
    SYSTEM_MAINTENANCE = "system_admin:maintenance"

    # Reporting and Analytics Permissions
    REPORTING_VIEW = "reporting:view"
    REPORTING_GENERATE = "reporting:generate"
    REPORTING_EXPORT = "reporting:export"
    REPORTING_CUSTOM = "reporting:custom"
    REPORTING_SCHEDULE = "reporting:schedule"

    # Audit and Compliance Permissions
    AUDIT_READ = "audit:read"
    AUDIT_EXPORT = "audit:export"
    AUDIT_CONFIGURE = "audit:configure"

    # Financial Permissions
    FINANCIAL_VIEW = "financial:view"
    FINANCIAL_APPROVE = "financial:approve"
    FINANCIAL_BUDGET = "financial:budget"

    # Maintenance Planning Permissions
    PLANNING_VIEW = "planning:view"
    PLANNING_CREATE = "planning:create"
    PLANNING_APPROVE = "planning:approve"
    PLANNING_SCHEDULE = "planning:schedule"

    # Emergency Response Permissions
    EMERGENCY_RESPOND = "emergency:respond"
    EMERGENCY_ESCALATE = "emergency:escalate"
    EMERGENCY_MANAGE = "emergency:manage"


class Role(Enum):
    """System roles with defined responsibilities"""

    TECHNICIAN = "Technician"
    SUPERVISOR = "Supervisor"
    AUDITOR = "Auditor"
    ADMIN = "Admin"


# Comprehensive Permission Matrix following Least Privilege
ROLE_PERMISSIONS: Dict[Role, List[Permission]] = {
    Role.TECHNICIAN: [
        # Assets - Can view assets assigned to them
        Permission.ASSET_READ,
        # Work Orders - Can create, view, and complete work orders
        Permission.WORK_ORDER_READ,
        Permission.WORK_ORDER_CREATE,
        Permission.WORK_ORDER_COMPLETE,
        # Inventory - Can view inventory for parts needed
        Permission.INVENTORY_VIEW,
        # Reporting - Can view basic reports
        Permission.REPORTING_VIEW,
        # Emergency - Can respond to emergencies
        Permission.EMERGENCY_RESPOND,
    ],
    Role.SUPERVISOR: [
        # Assets - Can read and update assets under supervision
        Permission.ASSET_READ,
        Permission.ASSET_WRITE,
        Permission.ASSET_REGISTER,
        Permission.ASSET_TRANSFER,
        # Work Orders - Full work order management except deletion
        Permission.WORK_ORDER_READ,
        Permission.WORK_ORDER_CREATE,
        Permission.WORK_ORDER_ASSIGN,
        Permission.WORK_ORDER_APPROVE,
        Permission.WORK_ORDER_COMPLETE,
        Permission.WORK_ORDER_RESCHEDULE,
        Permission.WORK_ORDER_PRIORITY_CHANGE,
        # Inventory - Can view and update inventory
        Permission.INVENTORY_VIEW,
        Permission.INVENTORY_UPDATE,
        Permission.INVENTORY_TRANSFER,
        # User Management - Can view team member profiles
        Permission.USER_VIEW_PROFILES,
        Permission.USER_VIEW_ACTIVITY,
        # Reporting - Can view and generate reports
        Permission.REPORTING_VIEW,
        Permission.REPORTING_GENERATE,
        Permission.REPORTING_EXPORT,
        # Planning - Can view and create maintenance plans
        Permission.PLANNING_VIEW,
        Permission.PLANNING_CREATE,
        Permission.PLANNING_SCHEDULE,
        # Financial - Can view costs
        Permission.FINANCIAL_VIEW,
        # Emergency - Can respond and escalate
        Permission.EMERGENCY_RESPOND,
        Permission.EMERGENCY_ESCALATE,
    ],
    Role.AUDITOR: [
        # Assets - Read-only access for compliance review
        Permission.ASSET_READ,
        # Work Orders - Read-only access for audit purposes
        Permission.WORK_ORDER_READ,
        # Inventory - Read-only access for inventory audits
        Permission.INVENTORY_VIEW,
        Permission.INVENTORY_AUDIT,
        # User Management - Can view user activity for compliance
        Permission.USER_VIEW_PROFILES,
        Permission.USER_VIEW_ACTIVITY,
        # Reporting - Full reporting access for compliance
        Permission.REPORTING_VIEW,
        Permission.REPORTING_GENERATE,
        Permission.REPORTING_EXPORT,
        Permission.REPORTING_CUSTOM,
        # Audit - Full audit access
        Permission.AUDIT_READ,
        Permission.AUDIT_EXPORT,
        # Financial - Can view financial data for audit
        Permission.FINANCIAL_VIEW,
        # Planning - Read-only access to plans
        Permission.PLANNING_VIEW,
    ],
    Role.ADMIN: [
        # Full access to all permissions
        Permission.ASSET_READ,
        Permission.ASSET_WRITE,
        Permission.ASSET_DELETE,
        Permission.ASSET_REGISTER,
        Permission.ASSET_TRANSFER,
        Permission.WORK_ORDER_READ,
        Permission.WORK_ORDER_CREATE,
        Permission.WORK_ORDER_ASSIGN,
        Permission.WORK_ORDER_APPROVE,
        Permission.WORK_ORDER_COMPLETE,
        Permission.WORK_ORDER_DELETE,
        Permission.WORK_ORDER_RESCHEDULE,
        Permission.WORK_ORDER_PRIORITY_CHANGE,
        Permission.INVENTORY_VIEW,
        Permission.INVENTORY_UPDATE,
        Permission.INVENTORY_PURCHASE,
        Permission.INVENTORY_AUDIT,
        Permission.INVENTORY_WRITE_OFF,
        Permission.INVENTORY_TRANSFER,
        Permission.USER_VIEW_PROFILES,
        Permission.USER_MANAGE_ACCOUNTS,
        Permission.USER_ASSIGN_ROLES,
        Permission.USER_DELETE_ACCOUNTS,
        Permission.USER_VIEW_ACTIVITY,
        Permission.SYSTEM_CONFIG,
        Permission.SYSTEM_BACKUP,
        Permission.SYSTEM_RESTORE,
        Permission.SYSTEM_LOGS,
        Permission.SYSTEM_MAINTENANCE,
        Permission.REPORTING_VIEW,
        Permission.REPORTING_GENERATE,
        Permission.REPORTING_EXPORT,
        Permission.REPORTING_CUSTOM,
        Permission.REPORTING_SCHEDULE,
        Permission.AUDIT_READ,
        Permission.AUDIT_EXPORT,
        Permission.AUDIT_CONFIGURE,
        Permission.FINANCIAL_VIEW,
        Permission.FINANCIAL_APPROVE,
        Permission.FINANCIAL_BUDGET,
        Permission.PLANNING_VIEW,
        Permission.PLANNING_CREATE,
        Permission.PLANNING_APPROVE,
        Permission.PLANNING_SCHEDULE,
        Permission.EMERGENCY_RESPOND,
        Permission.EMERGENCY_ESCALATE,
        Permission.EMERGENCY_MANAGE,
    ],
}


def get_role_permissions(role: Role) -> List[Permission]:
    """
    Get all permissions for a specific role

    Args:
        role: The role to get permissions for

    Returns:
        List of permissions for the role
    """
    return ROLE_PERMISSIONS.get(role, [])


def get_role_permissions_strings(role: Role) -> List[str]:
    """
    Get all permissions for a role as strings

    Args:
        role: The role to get permissions for

    Returns:
        List of permission strings
    """
    permissions = get_role_permissions(role)
    return [perm.value for perm in permissions]


def has_permission(role: Role, permission: Permission) -> bool:
    """
    Check if a role has a specific permission

    Args:
        role: The role to check
        permission: The permission to verify

    Returns:
        True if role has permission, False otherwise
    """
    role_perms = get_role_permissions(role)
    return permission in role_perms


def has_permission_string(role: Role, permission_string: str) -> bool:
    """
    Check if a role has a specific permission by string

    Args:
        role: The role to check
        permission_string: The permission string to verify

    Returns:
        True if role has permission, False otherwise
    """
    try:
        permission = Permission(permission_string)
        return has_permission(role, permission)
    except ValueError:
        return False


def get_all_permissions() -> List[Permission]:
    """Get all available permissions in the system"""
    return list(Permission)


def get_all_permission_strings() -> List[str]:
    """Get all available permissions as strings"""
    return [perm.value for perm in Permission]


def get_permissions_by_category() -> Dict[str, List[str]]:
    """
    Get permissions grouped by category

    Returns:
        Dictionary with categories as keys and permission lists as values
    """
    categories = {}

    for permission in Permission:
        category = permission.value.split(":")[0]
        if category not in categories:
            categories[category] = []
        categories[category].append(permission.value)

    return categories


def validate_role_permissions() -> Dict[str, Any]:
    """
    Validate the permission matrix for completeness and correctness

    Returns:
        Validation report
    """
    report = {
        "total_permissions": len(Permission),
        "total_roles": len(Role),
        "role_permission_counts": {},
        "categories": {},
        "validation_passed": True,
        "issues": [],
    }

    # Count permissions per role
    for role in Role:
        perms = get_role_permissions(role)
        report["role_permission_counts"][role.value] = len(perms)

    # Count permissions per category
    categories = get_permissions_by_category()
    for category, perms in categories.items():
        report["categories"][category] = len(perms)

    # Validation checks
    if report["role_permission_counts"][Role.ADMIN.value] < len(Permission):
        report["issues"].append("Admin role does not have all permissions")
        report["validation_passed"] = False

    if report["role_permission_counts"][Role.TECHNICIAN.value] > 10:
        report["issues"].append(
            "Technician role may have too many permissions (violates least privilege)"
        )

    if report["role_permission_counts"][Role.AUDITOR.value] == 0:
        report["issues"].append("Auditor role has no permissions")
        report["validation_passed"] = False

    return report


# Permission Matrix as Dictionary (for backward compatibility)
PERMISSION_MATRIX: Dict[str, List[str]] = {
    role.value: get_role_permissions_strings(role) for role in Role
}


# Enterprise Compliance Features
class AuditableAction:
    """Define actions that require audit logging"""

    CRITICAL_PERMISSIONS = [
        Permission.ASSET_DELETE,
        Permission.WORK_ORDER_DELETE,
        Permission.USER_DELETE_ACCOUNTS,
        Permission.SYSTEM_CONFIG,
        Permission.FINANCIAL_APPROVE,
        Permission.EMERGENCY_MANAGE,
    ]

    APPROVAL_REQUIRED_PERMISSIONS = [
        Permission.ASSET_DELETE,
        Permission.INVENTORY_WRITE_OFF,
        Permission.FINANCIAL_APPROVE,
        Permission.USER_ASSIGN_ROLES,
        Permission.SYSTEM_CONFIG,
    ]


def requires_audit(permission: Permission) -> bool:
    """Check if a permission requires audit logging"""
    return permission in AuditableAction.CRITICAL_PERMISSIONS


def requires_approval(permission: Permission) -> bool:
    """Check if a permission requires additional approval"""
    return permission in AuditableAction.APPROVAL_REQUIRED_PERMISSIONS


# Enterprise Role Hierarchy
ROLE_HIERARCHY = {
    Role.ADMIN: 4,  # Highest level
    Role.SUPERVISOR: 3,
    Role.AUDITOR: 2,
    Role.TECHNICIAN: 1,  # Lowest level
}


def can_manage_role(manager_role: Role, target_role: Role) -> bool:
    """
    Check if a manager role can manage a target role

    Args:
        manager_role: Role of the manager
        target_role: Role to be managed

    Returns:
        True if manager can manage target role
    """
    manager_level = ROLE_HIERARCHY.get(manager_role, 0)
    target_level = ROLE_HIERARCHY.get(target_role, 0)

    return manager_level > target_level
